// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package mysqldb

import (
	"context"
	"time"
)

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, position, done, created_at FROM item WHERE id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO item (id, name, position, done, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertItemParams struct {
	ID        string
	Name      string
	Position  int32
	Done      bool
	CreatedAt time.Time
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.Done,
		arg.CreatedAt,
	)
	return err
}

const maxPosition = `-- name: MaxPosition :one
SELECT CAST(COALESCE(MAX(position), 0) AS SIGNED) as max_position FROM item
`

func (q *Queries) MaxPosition(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxPosition)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE item SET name = ?, position = ?, done = ? WHERE id = ?
`

type UpdateItemParams struct {
	Name     string
	Position int32
	Done     bool
	ID       string
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.Position,
		arg.Done,
		arg.ID,
	)
	return err
}
