// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type Item struct {
	ID        string
	Name      string
	Position  int64
	Done      bool
	CreatedAt time.Time
}
