// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package ports

import (
	"time"
)

// ErrBadParams defines model for ErrBadParams.
type ErrBadParams struct {
	Fields *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"fields,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ItemPatch defines model for ItemPatch.
type ItemPatch struct {
	Done     *bool   `json:"done,omitempty"`
	Name     *string `json:"name,omitempty"`
	Position *int    `json:"position,omitempty"`
}

// ItemPost defines model for ItemPost.
type ItemPost struct {
	Name     string `json:"name"`
	Position *int   `json:"position,omitempty"`
}

// Todo item
type ItemResponse struct {
	// The date that the item was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Done flag
	Done *bool `json:"done,omitempty"`

	// Unique identifier for the given item.
	Id   string  `json:"id"`
	Name *string `json:"name,omitempty"`

	// Position for sort
	Position *int `json:"position,omitempty"`
}

// Todo items
type ItemsResponse []ItemResponse

// Page defines model for _page.
type Page int

// PerPage defines model for _per_page.
type PerPage int

// ItemId defines model for item_id.
type ItemId string

// GetItemsJSONBody defines parameters for GetItems.
type GetItemsJSONBody map[string]interface{}

// GetItemsParams defines parameters for GetItems.
type GetItemsParams struct {
	// Count items per page
	PerPage *PerPage `json:"_per_page,omitempty"`

	// Page number
	Page *Page `json:"_page,omitempty"`

	// Sort by fields
	Sort *string `json:"_sort,omitempty"`

	// Retrieve certain fields
	Fields *string `json:"_fields,omitempty"`

	// Filter by done
	Done *bool `json:"done,omitempty"`
}

// PostItemsJSONBody defines parameters for PostItems.
type PostItemsJSONBody ItemPost

// PatchItemsItemidJSONBody defines parameters for PatchItemsItemid.
type PatchItemsItemidJSONBody ItemPatch

// GetItemsJSONRequestBody defines body for GetItems for application/json ContentType.
type GetItemsJSONRequestBody GetItemsJSONBody

// PostItemsJSONRequestBody defines body for PostItems for application/json ContentType.
type PostItemsJSONRequestBody PostItemsJSONBody

// PatchItemsItemidJSONRequestBody defines body for PatchItemsItemid for application/json ContentType.
type PatchItemsItemidJSONRequestBody PatchItemsItemidJSONBody
