// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all items
	// (GET /items)
	GetItems(ctx echo.Context, params GetItemsParams) error
	// Create New User
	// (POST /items)
	PostItems(ctx echo.Context) error
	// Get Item Info by Item ID
	// (GET /items/{item_id})
	GetItemsItemId(ctx echo.Context, itemId ItemId) error
	// Update Item
	// (PATCH /items/{item_id})
	PatchItemsItemid(ctx echo.Context, itemId ItemId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemsParams
	// ------------- Optional query parameter "_per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "_per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _per_page: %s", err))
	}

	// ------------- Optional query parameter "_cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "_cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _cursor: %s", err))
	}

	// ------------- Optional query parameter "_sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "_sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _sort: %s", err))
	}

	// ------------- Optional query parameter "_fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "_fields", ctx.QueryParams(), &params.Fields)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _fields: %s", err))
	}

	// ------------- Optional query parameter "done" -------------

	err = runtime.BindQueryParameter("form", true, false, "done", ctx.QueryParams(), &params.Done)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter done: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItems(ctx, params)
	return err
}

// PostItems converts echo context to params.
func (w *ServerInterfaceWrapper) PostItems(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostItems(ctx)
	return err
}

// GetItemsItemId converts echo context to params.
func (w *ServerInterfaceWrapper) GetItemsItemId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItemsItemId(ctx, itemId)
	return err
}

// PatchItemsItemid converts echo context to params.
func (w *ServerInterfaceWrapper) PatchItemsItemid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchItemsItemid(ctx, itemId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/items", wrapper.GetItems)
	router.POST(baseURL+"/items", wrapper.PostItems)
	router.GET(baseURL+"/items/:item_id", wrapper.GetItemsItemId)
	router.PATCH(baseURL+"/items/:item_id", wrapper.PatchItemsItemid)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYaW/buBb9KwTf+yjbkuOgr3ooZroOjG5GF0wxnSCgpSubjUSqJJXYE/i/Dy5JLbbl",
	"JE5bTDEfEljicheee+4Rr2kii1IKEEbT+JqWTLECDCj7dJ5USkuFP1PQieKl4VLQmL4t2dcKiBsmmfu7",
	"YiolJVtwwXDakLwtuHGDXGmDQzCkAeW4w9cK1JoGVLACaNxYCqhOllAwNGnWJQ5po7hY0M0moOclqHPc",
	"Zt+jp7IShnADhSYlKGvskK1ml661FDJW5YbG4zCgBVvxoipoHIUhPnLhH4PaKy4MLEBZt9DqOU/3nZoa",
	"KMj0We1HycyydaNeFVAFXyuuIKWxURV0ncqkKpihMa0qO3M3JZt6sj2u50o9YekMj9AdppIlKMPBPmUc",
	"8tT+slk6MKEn8QEtQGuf9f1D8W/k/AskhrYvmFJsfftqbnJ89Vwpe/x7u2EOZ8wkS1xfcDHr+BwFOyGk",
	"UnTtzKXMgQncxiW9J7ZSau6O67rvbGv/WjcO+Si12c/pfc22kPjs9jjbcQWtHfDkHehSCt1TJB9kKm2N",
	"0N3EJQqYgfScmZ5VSyApM0DMkhlilmC3IFdME78Mq7qBKk4dGF7APl6D5oC2LTyTAkiWs0W7pHN0fZX1",
	"UXAkIJ6CMDzj4EgIfVvwSxDWQ/QKVqwobdaiSZSyyZgNJuPk4WDyIIwG8wfzZJAmpyfzbBJGp+mkG0Z/",
	"xbVAane22YioZY1XIBZmWfPGjae+HdDMj9g4tFSm63x0KwV18cLTXbQcQoq+A1Q0DVrC+K+CjMb0P6O2",
	"a4w8AY22oLdTOa2hXXpABoOkUtys3+NGDo4GXDHZvS0cgCno8MPSmNLxHxeZtAiWwrDEroKC8ZzGFC4X",
	"IPh6eJFDwcWvC3w9TGTRcvBzN4O8tDMsQLeyYDALj2dT2oaDr2hAL0FpNycahrhQliBYyWlMT4bhMMQK",
	"Y2Zpoxk1+VtAT339BoawPG+yjXVpO+g0daNTP9Btzp/7D6OdMmrb3Ca4fbLvvzh127v3UhkyXxPfPg60",
	"VI/YtnO15THAOUGD/P0mtmfyHRjF4RJIAsowLm6x3Yz2WT/a+AueG1AYseWqfpt+qM8gtvAeGtucYZG6",
	"IrBQGIdhDVsQFhWsLHOe2JMffdGOJPy+dsU2TuJresnyCiwUuvRNx2H0cBD+bzCefIgmcXQaj8d/0Jp6",
	"M5ZrcJx6V0rs6BVLcy2JRZuzTUB/52a5e1Rb3v0gy5vuAdzGTC0DWdbYkbMvaUCXwFKve19xcdFD0Y20",
	"JTkXF4cQ92cVhieJq/lfmiJ8NA7tAPxfQf7ICuI+NNJPgzewMoOndxbeAlZeWpPHcw0ogjMiJCmkAqJA",
	"V7nRw1t09afBDNRgdoywvnm7D9KwfGCX9rUWw3KS2H1l5rcuUFtxsbA9PLM1eKMVtDMJoz5lwCqzlIr/",
	"BSm1k072J72Qas7TFCzln7pK3JHuwoASLCfvQV2CIk6fWsxVRcHUuoe4DVto24Dt85nr9z0JeGqrlTAi",
	"4KpRKtusj/qupn3s7aDNE5muj2QMb8gqvrYia1XqPk+i7mfEXSrJSs+eIsL39vQEJKj4Vd0zGmn2eDYl",
	"RnrRuBX+Zo8co3uFmu7H+o9R43FZvYme7Dn5AB2kj20dsEp4Cikp2IqgzyT3OrWTqJq5Pzdfgi68zgcc",
	"Kly/lHBNUOQSvS7mMtcUG1w78RhQbX229oT/mmuNzPDOa1wyFU6l4/BPQAO+yt7AFfmonUjdIYJN4DXg",
	"6Np/9W8OqsFG/NgPrTZSpMr22wtbLj41tMndVcPwoH7Ef1N32/DNKuTfWGRvX35HLE3Cyf6MN9KQF7IS",
	"6Tc3HXevJDKJMrW9ZOrpP0d9MdQ3UljKZX3lspOK0t8E7GGTCQIrrk0Nxp6ehls2WGxuvu7X2l4zdeFA",
	"zzSpbxUaPLoXKMWPbW427L7uhgOk0qiAmpsT7GaVzUhfCzu2slxuXQsj0T3ry90g/nzlhcxIfIQ/utCs",
	"re9TbR7v9SXKLq/b2wtc7OqrUrm/m4hHo1wmLF9KbeKTMAxtUfn1192cY+fc/B0AAP//u74J2YcXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
