// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all items
	// (GET /items)
	GetItems(ctx echo.Context, params GetItemsParams) error
	// Create New Item
	// (POST /items)
	PostItems(ctx echo.Context) error
	// Get Item Info by Item ID
	// (GET /items/{item_id})
	GetItemsItemId(ctx echo.Context, itemId ItemId) error
	// Update Item
	// (PATCH /items/{item_id})
	PatchItemsItemid(ctx echo.Context, itemId ItemId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemsParams
	// ------------- Optional query parameter "_per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "_per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _per_page: %s", err))
	}

	// ------------- Optional query parameter "_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "_page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _page: %s", err))
	}

	// ------------- Optional query parameter "_sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "_sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _sort: %s", err))
	}

	// ------------- Optional query parameter "_fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "_fields", ctx.QueryParams(), &params.Fields)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _fields: %s", err))
	}

	// ------------- Optional query parameter "done" -------------

	err = runtime.BindQueryParameter("form", true, false, "done", ctx.QueryParams(), &params.Done)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter done: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItems(ctx, params)
	return err
}

// PostItems converts echo context to params.
func (w *ServerInterfaceWrapper) PostItems(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostItems(ctx)
	return err
}

// GetItemsItemId converts echo context to params.
func (w *ServerInterfaceWrapper) GetItemsItemId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItemsItemId(ctx, itemId)
	return err
}

// PatchItemsItemid converts echo context to params.
func (w *ServerInterfaceWrapper) PatchItemsItemid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchItemsItemid(ctx, itemId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/items", wrapper.GetItems)
	router.POST(baseURL+"/items", wrapper.PostItems)
	router.GET(baseURL+"/items/:item_id", wrapper.GetItemsItemId)
	router.PATCH(baseURL+"/items/:item_id", wrapper.PatchItemsItemid)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYbW/bthP/KgT//5eyLTnOumoosD4ORp+MtsOGdUFAS2eLjUQqJOXGC/zdBx71ZJtO",
	"4jTFhr0xLPJ4dzz+fndHXtNEFqUUIIym8TUtmWIFGFD4dV6yJdg/KehE8dJwKWhMZ2wJRFTFHBQNKLdD",
	"lxWoNQ2oYAXQuF4YUJ1kUDCnYcGq3NA4CmjBrnhRFTSOwjCgBRf1V0DNurTLuTCwBEU3m4Cel6AO+PFc",
	"VsIQbqDQpARFaqN+hxotXqfG4bZXt7tlrZ7zdN+pqYGCTF80fpTMZJ0bzaqAKrisuIKUxkZV0HdqIVXB",
	"DI1pVaFkbVwbxcWSbqxxJ4xH9FKpZyyd2WNzB6hkCcpwwC9QSir7Z1dJ34HPtdhZQA03uZV7iQOtbTn/",
	"AomhmwB3N2MmyazSgotZz1wU7FhPpYCe8bmUOTBh1bhw7LkV0FJq7gJ57Yt641/nxiEfpTb74biv2X6s",
	"UMfZjivW2gFPPoAupdAe+H6SqUT00t3AJQqYgfScGc+qDEjKDBCTMUNMBqiCfGWa1MuGNOhAZEUHhhew",
	"j6SgPaBtCy+kALLI2bJb0js6H+Z/FfyyAsJTEIYvOCiykAp9W/IVCPTQegVXrCgxatEkStlkzAaTcfJ4",
	"MHkURoP5o3kySJPTk/liEkan6aS/DT8XOiB1mjEaEUU+vwGxNFnD6BtPfSfD1TO4Dy2V6Tsf3Zoc+njh",
	"6S5aDiFF3wEqmrrUgzD5v4IFjen/Rl0OH9WpYbQFvR3mdIZaT5hSbI2+a0gqxc36o1Xk4GjAkQl1IxyA",
	"Kejlh8yY0mUmLhYSESyFYQmugoLxnMYUVksQfD28yKHg4uelHR4msuiy40snQV6jBAJ0KwrGRuHpbEq7",
	"7dghGtAVKO1komFoF8oSBCs5jenJMByGlmHMZLibURu/JXj49QsYwvK8jbblJbNz09TNTuuJfqn87D+M",
	"TmTUFaBNcAfhRnDbt49SGTJfkwWHPNWHSl2N166idOQYWJmgxf1+cdkz+QGM4rACkoAyjItbbLezPutH",
	"G3/FcwPK7hgzld9mPeUzaEurJ4l5AgtMJZk1hEr9hi4PWJlXa89mzlwaAG2eyXTdcAIEQo6VZc4ThNXo",
	"i3YZqFO9kx02LqU4yiJwx2F4B4W1h7hiG9XxNV2xvAIEbr/Y0HEYPR6EPw7Gk0/RJI5O4/H4D9oUigXL",
	"NbgKcNcE3ut7MCl3KTfanG0C+hs32S60trz7TpY3/aO8LY92+RKPYhs671/TgGbA0rpnfsPFhbdl5gKP",
	"h+RcXBxiyJ9VGJ4kLkO5LPAksmPjH9r88WQcohT8pCB/oiFf+JhEfx/M7tC772FuWwOoA1oOdN43q/sk",
	"DcsHuNRX4QzLSdLpvVGdVTgJI18nwiqTScX/gpSi0Mm+0Cup5jxNAUvMqePSThMvDCjBcvIR1AoUcf0w",
	"oqYqCqbWnkJh2FJjwcfvM9dfeHb6HPlGGBHwte2MtquM7SebMnNcEulzvjaEHWbHqaYLdheVqH+huAsX",
	"sNX10MCOY8cnIAGtmWqqVNsKPp1NiZF1k7q1/f30Ft1rq+n+Xv+x5HZcVG9KMHhO9Qbpw+F+Mh4fGeQV",
	"y3nqclh7r2wDXY9gTGJSsCuSY/NNuCa2/SZ6Xcxlro/B29bd1hOZt1xrLpbkQ91uk6lwFwY7/S3Urpnz",
	"Dr6SpmHfIfcmqPvI0XV9p98c7CjbFgova52LRC569zdbCO1XYa+1dlfcPSQMD/ag9mfq3hK+uTf4LxLn",
	"/euHpEs42Zd4Jw15JSuRfnMhca9GYiFtD9o9IXlqylG3jua9yXajZfNssxOKsn5N2MMmEwSuuDYNGD11",
	"yqpssdi+a92vXL1l6sKBnmnSvEy0eHQDtqE/tmDhtn0Vy044g93ri61QFUbEV5aOZZaLrStLJLonv9z7",
	"4L+0LtU7/N5EQ1sPw7Ya74fyOr6A2MWOX5XK6/eNeDTKZcLyTGoTn4RhiKSq11/3Y67p5mzzdwAAAP//",
	"+utiFVkXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
