// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all items
	// (GET /items)
	GetItems(ctx echo.Context, params GetItemsParams) error
	// Create New Item
	// (POST /items)
	PostItems(ctx echo.Context) error
	// Get Item Info by Item ID
	// (GET /items/{item_id})
	GetItemsItemId(ctx echo.Context, itemId ItemId) error
	// Update Item
	// (PATCH /items/{item_id})
	PatchItemsItemid(ctx echo.Context, itemId ItemId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemsParams
	// ------------- Optional query parameter "_per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "_per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _per_page: %s", err))
	}

	// ------------- Optional query parameter "_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "_page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _page: %s", err))
	}

	// ------------- Optional query parameter "_sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "_sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _sort: %s", err))
	}

	// ------------- Optional query parameter "_fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "_fields", ctx.QueryParams(), &params.Fields)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter _fields: %s", err))
	}

	// ------------- Optional query parameter "done" -------------

	err = runtime.BindQueryParameter("form", true, false, "done", ctx.QueryParams(), &params.Done)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter done: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItems(ctx, params)
	return err
}

// PostItems converts echo context to params.
func (w *ServerInterfaceWrapper) PostItems(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostItems(ctx)
	return err
}

// GetItemsItemId converts echo context to params.
func (w *ServerInterfaceWrapper) GetItemsItemId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItemsItemId(ctx, itemId)
	return err
}

// PatchItemsItemid converts echo context to params.
func (w *ServerInterfaceWrapper) PatchItemsItemid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "item_id" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithLocation("simple", false, "item_id", runtime.ParamLocationPath, ctx.Param("item_id"), &itemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter item_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchItemsItemid(ctx, itemId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/items", wrapper.GetItems)
	router.POST(baseURL+"/items", wrapper.PostItems)
	router.GET(baseURL+"/items/:item_id", wrapper.GetItemsItemId)
	router.PATCH(baseURL+"/items/:item_id", wrapper.PatchItemsItemid)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYbW/bthP/KgT//5eyLTnOumoosD4ORp+MtsOGdUFAS2eLjUQqJOXGC/zdBx71ZJtO",
	"4jTFhr0xLPJ4dzz+7u5HXtNEFqUUIIym8TUtmWIFGFD4dV6yJdg/KehE8dJwKWhMZ2wJRFTFHBQNKLdD",
	"lxWoNQ2oYAXQuF4YUJ1kUDCnYcGq3NA4CmjBrnhRFTSOwjCgBRf1V0DNurTLuTCwBEU3m4Cel6AO+PFc",
	"VsIQbqDQpARFaqN+hxotXqfG4bZXt7tlrZ7zdN+pqYGCTF80fpTMZJ0bzaqAKrisuIKUxkZV0HdqIVXB",
	"DI1pVaFkbVwbxcWSbqxxJ4xH9FKpZyyd2WNzB6hkCcpwwC9QSir7Z1dJ34HPtdhZQA03uZV7iQOtbTn/",
	"AomhmwB3N2MmyazSgotZz1wU7FhPpYCe8bmUOTBh1bhw7LkV0FJq7gJ57Yt641/nxiEfpTb74biv2X6s",
	"UMfZjivW2gFPPoAupdAe+H6SqUT00t3AJQqYgfScGc+qDEjKDBCTMUNMBqiCfGWa1MuGNOhAZEUHhhew",
	"j6SgPaBtCy+kALLI2bJb0js6H+Z/FfyyAsJTEIYvOCiykAp9W/IVCPTQegVXrCgxatEkStlkzAaTcfJ4",
	"MHkURoP5o3kySJPTk/liEkan6aS/DX8udEDqNGM0Ior5/AbE0mRNRt946jsVrp7BfWipTN/56Nbi0McL",
	"T3fRcggp+g5Q0dSVHoTJ/xUsaEz/N+pq+KguDaMt6O1kTmeo9YQpxdbou4akUtysP1pFDo4GXDKhboQD",
	"MAW9+pAZU7rKxMVCIoKlMCzBVVAwntOYwmoJgq+HFzkUXPy8tMPDRBZddXzpJMhrlECAbkXB2Cg8nU1p",
	"tx07RAO6AqWdTDQM7UJZgmAlpzE9GYbD0GYYMxnuZtTGbwme/PoFDGF53kbb5iWzc9PUzU7riX6r/Ow/",
	"jE5k1DWgTXAH4UZw27ePUhkyX5MFhzzVh1pdjdeuo3TJMbAyQYv7/eayZ/IDGMVhBSQBZRgXt9huZ33W",
	"jzb+iucGlN0xViq/zXrKZ9C2Vk8R8wQWmEoyawiV+g1dHrAyr9aezZzZMuDSDME2DsMmMUAg7lhZ5jxB",
	"bI2+aFeGaq24YhuJ8TVdsbwCBFu/QdBxGD0ehD8OxpNP0SSOTuPx+A/aFPcFyzW4qn3XotvjKlhIuzIZ",
	"bc42Af2Nm2wXDlvefSfLm374b6t9XY3DurR93O9f04BmwNKa577h4sJLc7nA4yE5FxeHUP1nFYYniasq",
	"LnOfRHZs/EOb80/GIUrBTwryJxryhQ/99PfB7A58u/PBqwHUAS0H2PLN6j5Jw/IBLvV1JcNyknR6b1Rn",
	"FU7CyMceWGUyqfhfkFIUOtkXeiXVnKcpYFs4dbm0Q7yFASVYTj6CWoEijsMiaqqiYGrtKe6GLTU2afw+",
	"c5zAs9PnmG+EEQFfWzaz3RksB2xag+3/oM0zma6PzPnaELLCLqca5uouF1H/EnCXXEB66kkDO44sTUAC",
	"WjPVdJaWvj2dTYmRNbHc2v5mr7xF99pqur/Xf6y4HRfVmwoMnlO9QfpwuJ+Mx0cGecVynroa1t4F20DX",
	"IxiTmBTsiuRImAnXxFJmotfFXOb6GLxt3Uc9kXnLteZiST7UFJlMhSP5dvpbUrvOnHfwlTQkeye5N0HN",
	"/UbX9T18c5AFtrQHL1idi0Quencu2wjtV2GvonZX3F3+hwd5o/2Zuvv/N3OD/2LivH/9kOkSTvYl3klD",
	"XslKpN/cSNxLj1hIyxu7Zx9PTznqptC8EVkGWTZPLTuhKOsXgD1sMkHgimvTgNHTp6zKFovtW9T92tVb",
	"pi4c6JkmzWtCi0c3YEn4sQ0Lt+3rWHbCGexeTGyHqjAivrZ0bGa52Lq2RKJ75pd70/uX9qV6h9870dDW",
	"w2RbjfdDdR1fLexil1+Vyus3iXg0ymXC8kxqE5+EYYhJVa+/7sdc083Z5u8AAAD//8/lzuANFwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
